[project]
name = "lazy-robot-loader"
version = "0.0.0"
description = "Lazy DataLoader for LeRobot"
readme = "README.md"
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering",
]
