name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      LAZY_ROBOT_LOADER_CACHE_DIR: /tmp/.lrl-cache
    steps:
      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
      - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size: 1G
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: /tmp/.lrl-cache
          key: lrl-${{ hashFiles('tests/*.py') }}
          restore-keys: |
            lrl-
      - run: nix develop -c uv python pin ${{ matrix.py }}
      - run: nix develop -c make OUT="$GITHUB_STEP_SUMMARY" ci
