name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      LAZY_ROBOT_LOADER_CACHE_DIR: /tmp/.lrl-cache
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Cache UV
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ runner.arch }}
      - name: Cache Lazy Robot Loader (HF)
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: /tmp/.lrl-cache
          key: lrl-${{ hashFiles('tests/*.py') }}
          restore-keys: |
            lrl-
      - name: Cache DuckDB Extensions
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: /home/runner/.duckdb/extensions
          key: duckdb-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            duckdb-${{ runner.os }}-${{ runner.arch }}
      - name: Install Hatch
        uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5
      - name: Run Test
        run: |
          { echo '```'; hatch test --all; echo '```'; } >> "$GITHUB_STEP_SUMMARY"
